#!/bin/sh
#
# script to update Photran versions
#
# Usage: update_versions photran_version
#
# photran_version - new version string for Photran (e.g. "5.0.1")
#
# Note: a "qualifier" suffix will automatically be added to the version where appropriate
#

TMP_DIR=/tmp

if [ $# -lt 1 ]; then
	echo "usage: update_versions photran_version"
	exit 1
fi

photran_version=$1

PHOTRAN_FEATURES="\
	org.eclipse.photran-feature \
	org.eclipse.photran.intel-feature \
	org.eclipse.photran.xlf-feature \
	org.eclipse.rephraserengine-feature"

update_feature() {
	sed -e "s/^\([ \t]*\)version=\"[0-9]\.[0-9]\.[0-9]\.qualifier\"/\1version=\"$2\.qualifier\"/" < $1/feature.xml > $TMP_DIR/${1}_feature.xml
	mv $TMP_DIR/${1}_feature.xml $1/feature.xml
}

for feature in $PHOTRAN_FEATURES; do
	echo "Updating $feature..."
	update_feature $feature $photran_version
done

(cd org.eclipse.photran.repo && ant -DnewVersion="$1" -f fixModules.xml)

exit 0
